### ISSUE TITLE
Parcel (the transformer?) does not recover after an error in an imported AS file

### ISSUE THREAD

**Issue by dipdowel** [dipdowel/parcel-transformer-assemblyscript-codument#8]
## Summary
Either Parcel or the transformer does not recover after an error occurs in an AssemblyScript file imported in `index.as.ts`

## Steps to reproduce
1. Clone [the project template](https://github.com/dipdowel/assemblyscript-parcel-template.git)
2. Change directory to `assemblyscript-parcel-template`
3. `yarn` or `npm install`
4. `yarn start` or `npm run start`
5. Open `http://localhost:1234/` in your browser
6. Open `assembly/index.as.ts` in your IDE 
8. After line `const result = add16bit(<i16>a, <i16>b);` insert `const t: i32;`
9. Save and observer the error in the terminal and in your browser console 
10. Remove line `const t: i32;` from `assembly/index.as.ts` and save the file.

### State at this point
Parcel should successfully recompile your AS code and the error message should disappear form the terminal and from the browser console.

11. Open `assembly/helpers/add-16bit.ts` in your IDE 
12. Before line `return a + b;` insert `const t: i32;` 
13. Save and observer the error in the terminal and in your browser console
14. Remove line `const t: i32;` from `assembly/helpers/add-16bit.ts` and save the file.

### Expected result
Parcel should successfully recompile your AS code and the error message should disappear form the terminal and from the browser console.

### Actual result
Parcel does not seem to detect the change in `assembly/helpers/add-16bit.ts`, the error message remains in the terminal and in the browser console. Please see the screenshot below:

![01-06-2023_error-not-recovered](https://github.com/dipdowel/parcel-transformer-assemblyscript-codument/assets/5098942/6b1727ca-4ee9-435d-a28b-72c094001db2)

### A work-around
If you then make any change in  `index.as.ts` and save it,  the project will be recompiled and reloaded as expected.

**Comment by dipdowel** [comment]
If you then introduce an error in `index.as.ts`, save the file, then fix the error, then the project gets recompiled and reloaded as expected.

**Comment by mischnic** [comment]
Currently, you do:
- Run the ASC compiler
- if there's an error, throw
- add the file invalidations, call `asset.setCode`, ...

Instead, you need to
- Run the ASC compiler
- add the file invalidations
- if there's an error, throw
- call `asset.setCode`, ...


E.g. https://github.com/mischnic/parcel-transformer-assemblyscript-codument/commit/420cd42c1c63e105bd4c6ef18902e856b9cc08e3

**Comment by dipdowel** [comment]
> Currently, you do:
>  <omitted>
> E.g. [mischnic@420cd42](https://github.com/mischnic/parcel-transformer-assemblyscript-codument/commit/420cd42c1c63e105bd4c6ef18902e856b9cc08e3)

Hey @mischnic, thanks a lot for the suggested solution, it did the trick! Also, thank you so much for improving the quality of the code that surrounded your changes.
Here's the merged PR with your suggestion: https://github.com/dipdowel/parcel-transformer-assemblyscript-codument/pull/9
